# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 471fd6da00eafc4da5af679e7a1d1058eee71dffcad616ac241f0592b730c1fd493b175e9cf65ec8a0c717afb4e8fec468582c7cfe8cb09981e79c094a46f4c2

test:
  secret_key_base: dc0931111bf911b77340c4adfad03f2e4f8712bb8f937d911c25ac1f4d6fd349c6d01343d032f1fe05ad86bec69c86a5d7709086ecd38ea5a35ecf24bf9bc9a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
